name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push it to Docker Hub.
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "krisb20" --password-stdin
        docker image build -t krisb20/myapp:latest .
        docker push krisb20/myapp:latest
